name: Android Workflow

on:
    workflow_call

env:
    ARTIFACT_NAME: ${{ 'android_artifact' }}
    EXPORT_PATH_STAGING: ${{ 'android/app/build/outputs/bundle/release/' }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install Java
              uses: actions/setup-java@v2
              with:
                java-version: "11"
                distribution: "adopt"
                cache: "gradle"

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"

            - name: Restore node_modules from cache
              uses: actions/cache@v2
              id: yarn-cache
              with:
                path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                    ${{ runner.os }}-yarn-

            - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
              run: yarn install --frozen-lockfile

            - name: Make Gradlew Executable
              run: cd android && chmod +x ./gradlew

            - name: Build Android
              run: |
                cd android && ./gradlew bundleRelease --no-daemon

            - name: list files inside android/app/build/outputs/
              run: ls -R android/app/build/outputs/
            
            - name: Upload application
              uses: actions/upload-artifact@v3
              with:
                name: ${{ env.ARTIFACT_NAME }}
                path: ${{ env.EXPORT_PATH_STAGING }}
                retention-days: 3
