name: Deployment IOS

on: [push]

env:
    APP_NAME_STAGING: ${{ 'medev-weather-app/ENV_STAGING' }}
    APP_CENTER_TOKEN_STAGING: ${{ secrets.APP_CENTER_TOKEN_STAGING}}
    TESTING_GROUP_STAGING: ${{ 'ENV_STAGING' }}
    ARTIFACT_NAME: ${{ 'app_artifact' }}

jobs:
    build-test:
        name: IOS Production Build
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Create Dummy Artifact
              run: |
                # Create a dummy file (e.g., a text file)
                echo "This is a dummy artifact" > dummy.ipa

            - name: Upload application
              uses: actions/upload-artifact@v3
              with:
                name: app_artifact
                path: dummy.ipa
                retention-days: 3
            

    deploy-ios:
        needs: [build-test]
        if: success()
        name: Deploy IOS
        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v3
          
        - name: download artifact 
          uses: actions/download-artifact@v3
          with:
            name: ${{ env.ARTIFACT_NAME }}
            
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Upload to App Center STAGING
          uses: wzieba/AppCenter-Github-Action@v1
          with:
            appName: ${{ env.APP_NAME_STAGING }}
            token: ${{ env.APP_CENTER_TOKEN_STAGING }}
            group: ${{ env.TESTING_GROUP_STAGING }}
            # file: ${{ runner.temp }}/build/WeatherApp.ipa
            file: dummy.txt
            notifyTesters: true
            debug: false
